development: &non_production_settings
  site_url: http://localhost:3000
  site_name: Bort
  admin_email: bort@bort.com
  
test:
  <<: *non_production_settings
  
production:
  site_url: http://www.example.com
  site_name: Bort
  admin_email: bort@bort.com
